{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.exifinterface",
    "module": "exifinterface",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6978002"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "exifinterface-1.3.2.aar",
          "url": "exifinterface-1.3.2.aar",
          "size": 60708,
          "sha512": "2803d8e64d99cde48a07b5795197ebc8e7fc501d6a031c1d8c1dc8d3b6063a9ef224d8569553ff7cf60a589483a8a0ee4cb75a9c1394c94a9f27b775dcba5bcd",
          "sha256": "8770c180103e0b8c04a07eb4c59153af639b09eca25deae9bdcdaf869d1e5b6b",
          "sha1": "ce8e52ca0749a3b6d07758a26e1cc642180bb4d7",
          "md5": "4362ef84379b9fb09ef236b9f6b20f54"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "exifinterface-1.3.2.aar",
          "url": "exifinterface-1.3.2.aar",
          "size": 60708,
          "sha512": "2803d8e64d99cde48a07b5795197ebc8e7fc501d6a031c1d8c1dc8d3b6063a9ef224d8569553ff7cf60a589483a8a0ee4cb75a9c1394c94a9f27b775dcba5bcd",
          "sha256": "8770c180103e0b8c04a07eb4c59153af639b09eca25deae9bdcdaf869d1e5b6b",
          "sha1": "ce8e52ca0749a3b6d07758a26e1cc642180bb4d7",
          "md5": "4362ef84379b9fb09ef236b9f6b20f54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exifinterface-1.3.2-sources.jar",
          "url": "exifinterface-1.3.2-sources.jar",
          "size": 62381,
          "sha512": "51c78dd9090a3b1d930fb2b9f43e26e6f8148ae759b74a235d42c2c49cd1e6242ca6b2b2b558ae94e3081a1c1fe0f2c1ee85f26dace39659f210bbdb160c699f",
          "sha256": "8f59d756a6bc00ced77ff73540106f42a19cb38fa231503f127a962de7db28b6",
          "sha1": "1bd0ec4a0281e75ef08c8317c92f800e48b0fd19",
          "md5": "c9b18d5642f64c96cdef2e9d6141877c"
        }
      ]
    }
  ]
}
