{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bumptech.glide",
    "module": "annotations",
    "version": "4.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-4.16.0.jar",
          "url": "annotations-4.16.0.jar",
          "size": 4305,
          "sha512": "4f0a89fa84ef35c7d636a142e849b78e7ac80cd9a6f47fa6d73b5f7110db369fcc4e18c1c6af650a343fa70e347af6f9a73084c12c59112c195aeb828ea557c0",
          "sha256": "c59e39b1b31b4d5592277cd90012149d740b569d4338f56443cac82c3fbda3d1",
          "sha1": "90730f6498299d207aa0878124ab7585969808f0",
          "md5": "10ee49b0d5c18657702255e39a57ab31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-4.16.0.jar",
          "url": "annotations-4.16.0.jar",
          "size": 4305,
          "sha512": "4f0a89fa84ef35c7d636a142e849b78e7ac80cd9a6f47fa6d73b5f7110db369fcc4e18c1c6af650a343fa70e347af6f9a73084c12c59112c195aeb828ea557c0",
          "sha256": "c59e39b1b31b4d5592277cd90012149d740b569d4338f56443cac82c3fbda3d1",
          "sha1": "90730f6498299d207aa0878124ab7585969808f0",
          "md5": "10ee49b0d5c18657702255e39a57ab31"
        }
      ]
    }
  ]
}
