{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.exifinterface",
    "module": "exifinterface",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "9550984"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exifinterface-1.3.6.aar",
          "url": "exifinterface-1.3.6.aar",
          "size": 64328,
          "sha512": "3b43772ee7d69f5d4b2c24c84b32ddf100eb53207fcbeb47ba9b72769dbae842b6603728f7bae3ed66c07a8e759e8a4409e9391c8093ec9a34e1b2ce8dbae9f7",
          "sha256": "1804105e9e05fdd8f760413bad5de498c381aa329f4f9d94c851bc891ac654c6",
          "sha1": "66c4f85fbe44c6556b05ecd28ea1af00cff3655e",
          "md5": "3379eefb116e6a1bd537ff0b85c1e694"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "exifinterface-1.3.6.aar",
          "url": "exifinterface-1.3.6.aar",
          "size": 64328,
          "sha512": "3b43772ee7d69f5d4b2c24c84b32ddf100eb53207fcbeb47ba9b72769dbae842b6603728f7bae3ed66c07a8e759e8a4409e9391c8093ec9a34e1b2ce8dbae9f7",
          "sha256": "1804105e9e05fdd8f760413bad5de498c381aa329f4f9d94c851bc891ac654c6",
          "sha1": "66c4f85fbe44c6556b05ecd28ea1af00cff3655e",
          "md5": "3379eefb116e6a1bd537ff0b85c1e694"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exifinterface-1.3.6-sources.jar",
          "url": "exifinterface-1.3.6-sources.jar",
          "size": 64738,
          "sha512": "60dcee1a997b7b07f888e581040c6051531f311664771404057bde23001d94aeb898cf30b02cd950a990a2706f204312a69cfa23ebbb1edbb942898375a620fd",
          "sha256": "90df2b40e195bce9d2294ff0224f3f37d65d253ea7e804a11a835ddb3929dffa",
          "sha1": "aeb56286a5af00c1fa61258576e5b8f03a63d05d",
          "md5": "2c91806e2f60d707c67d1c5fc45af705"
        }
      ]
    }
  ]
}
